#!/bin/sh -x
set -eu

OUTPUT_FILE="${SRCROOT:-$(pwd)}/PictureViewer/BuildInfo.swift"
BUILD_TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S %Z')"
BUILD_IDENTIFIER="$(date '+%Y%m%d-%H%M%S-%Z')"

cat > "$OUTPUT_FILE" <<EOF
//
//  BuildInfo.swift
//  PictureViewer
//
//  Generated by update_build_info.sh. Do not edit by hand.
//

import Foundation

struct BuildInfo {
    static let buildTimestamp = "$BUILD_TIMESTAMP"
    static let buildIdentifier = "$BUILD_IDENTIFIER"

    static var appVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "Unknown"
    }

    static var bundleVersion: String {
        Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "Unknown"
    }
}
EOF
