//
//  BuildInfo.swift
//  PictureViewer
//
//  Generated by update_build_info.sh. Do not edit by hand.
//

import Foundation

struct BuildInfo {
    static let buildTimestamp = "2026-06-08 17:55:26 EDT"
    static let buildIdentifier = "20260608-175527-EDT"

    static var appVersion: String {
        Bundle.main.infoDictionary?["CFBundleShortVersionString"] as? String ?? "Unknown"
    }

    static var bundleVersion: String {
        Bundle.main.infoDictionary?["CFBundleVersion"] as? String ?? "Unknown"
    }
}
